name: Testing the application
on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - master
            - dev
        types: [synchronize, opened, reopened, ready_for_review]

jobs:
    install-all-packages-front:
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        name: Install All Packages Front
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: install all packages
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
                  dir: 'client'
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: client/node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
    
    code-linting-front:
        needs: [install-all-packages-front]
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        name: Code linting front
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: client/node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Run eslint
              uses: borales/actions-yarn@v4
              with:
                  cmd: lint
                  dir: 'client'

    typings-front:
        needs: [code-linting-front]
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        name: Typings front
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: client/node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Run typing app
              uses: borales/actions-yarn@v4
              with:
                  cmd: tsc
                  dir: 'client'

    build-front:
        needs: [typings-front]
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        name: Building front
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: client/node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Build the front
              uses: borales/actions-yarn@v4
              with:
                  cmd: build
                  dir: 'client'
